// Convert Pinscreen head OBJ -> src/headmodel.ts (compact TS module)
// and render ASCII previews (front / right / top) for visual inspection.
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(__dirname, '..', 'assets', 'pinscreen_head.obj');
const OUT = path.join(__dirname, '..', 'src', 'headmodel.ts');

interface RawVert { x: number; y: number; z: number }

const verts: RawVert[] = [];
const tris: [number, number, number][] = [];

for (const line of fs.readFileSync(SRC, 'utf8').split('\n')) {
  const t = line.trim().split(/\s+/);
  if (t.length === 0) continue;
  if (t[0] === 'v') {
    verts.push({ x: parseFloat(t[1]), y: parseFloat(t[2]), z: parseFloat(t[3]) });
  } else if (t[0] === 'f') {
    const idx = t.slice(1, 4).map(s => parseInt(s.split('/')[0], 10) - 1);
    if (idx.every(i => i >= 0 && i < verts.length)) tris.push([idx[0], idx[1], idx[2]]);
  }
}

console.log(`parsed ${verts.length} verts, ${tris.length} tris`);

// ---- centroid + normalization to unit head (radius ~1) ----
const cx = verts.reduce((s, v) => s + v.x, 0) / verts.length;
const cy = verts.reduce((s, v) => s + v.y, 0) / verts.length;
const cz = verts.reduce((s, v) => s + v.z, 0) / verts.length;
let maxR = 0;
for (const v of verts) {
  const r = Math.hypot(v.x - cx, v.y - cy, v.z - cz);
  if (r > maxR) maxR = r;
}
const scale = 1 / maxR;

const V = verts.map(v => [
  (v.x - cx) * scale,
  (v.y - cy) * scale,
  (v.z - cz) * scale,
] as [number, number, number]);

// ---- per-vertex normals (accumulate from triangles) ----
const N = V.map(() => [0, 0, 0] as [number, number, number]);

// Bake a Z-flip so the FACE points toward +Z (camera direction).
const flipZ = (p: [number, number, number]): [number, number, number] => [-p[0], p[1], -p[2]];
for (let i = 0; i < V.length; i++) V[i] = flipZ(V[i]);

for (const [a, b, c] of tris) {
  const [ax, ay, az] = V[a], [bx, by, bz] = V[b], [cx2, cy2, cz2] = V[c];
  const ux = bx - ax, uy = by - ay, uz = bz - az;
  const wx = cx2 - ax, wy = cy2 - ay, wz = cz2 - az;
  const n = [
    uy * wz - uz * wy,
    uz * wx - ux * wz,
    ux * wy - uy * wx,
  ] as [number, number, number];
  const len = Math.hypot(n[0], n[1], n[2]) || 1;
  for (let i = 0; i < 3; i++) {
    N[a][i] += n[i] / len;
    N[b][i] += n[i] / len;
    N[c][i] += n[i] / len;
  }
}

// Make all normals point OUTWARD (away from centroid) — important for correct shading.
const P = V;
for (let i = 0; i < P.length; i++) {
  let len = Math.hypot(N[i][0], N[i][1], N[i][2]);
  if (len < 1e-8) { N[i] = [0, 1, 0]; len = 1; }
  for (let j = 0; j < 3; j++) N[i][j] /= len;
  const dot = N[i][0] * P[i][0] + N[i][1] * P[i][1] + N[i][2] * P[i][2];
  if (dot < 0) for (let j = 0; j < 3; j++) N[i][j] = -N[i][j];
}

// ---- axis statistics for orientation report ----
const min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
for (const [x, y, z] of P) {
  min[0] = Math.min(min[0], x); max[0] = Math.max(max[0], x);
  min[1] = Math.min(min[1], y); max[1] = Math.max(max[1], y);
  min[2] = Math.min(min[2], z); max[2] = Math.max(max[2], z);
}
console.log('bounds after normalize:');
console.log('  X:', min[0].toFixed(3), '..', max[0].toFixed(3));
console.log('  Y:', min[1].toFixed(3), '..', max[1].toFixed(3));
console.log('  Z:', min[2].toFixed(3), '..', max[2].toFixed(3));

// ---- write headmodel.ts ----
const q = (v: number) => Math.round(v * 100000) / 100000;
let out = `// Auto-generated by tools/convert_head.ts — do not edit by hand.
// Source: assets/pinscreen_head.obj (Pinscreen Generic Head, avatarneo.com)
// Normalized to unit head (radius ~1), centroid at origin. Y up.

export const HEAD_N = ${verts.length};
export const HEAD_TRI_COUNT = ${tris.length};

export const HEAD_POS = new Float32Array([
${P.map(([x, y, z]) => `${q(x)}, ${q(y)}, ${q(z)},`).join('\n')}
]);

export const HEAD_NRM = new Float32Array([
${N.map(([x, y, z]) => `${q(x)}, ${q(y)}, ${q(z)},`).join('\n')}
]);

export const HEAD_TRI = new Uint32Array([
${tris.map(([a, b, c]) => `${a}, ${b}, ${c},`).join('\n')}
]);
`;
fs.writeFileSync(OUT, out);
console.log(`wrote ${OUT} (${(out.length / 1024).toFixed(0)} KB)`);

// ============================================================
// ASCII previews
// ============================================================

const RAMP = ' .,:;~+*#%@';
const LIGHT = (() => { const l = [0.45, 0.85, 0.55]; const n = Math.hypot(...l); return l.map(x => x / n); })();

function rx(p: [number, number, number], a: number): [number, number, number] {
  const c = Math.cos(a), s = Math.sin(a);
  return [p[0], p[1] * c - p[2] * s, p[1] * s + p[2] * c];
}
function ry(p: [number, number, number], a: number): [number, number, number] {
  const c = Math.cos(a), s = Math.sin(a);
  return [p[0] * c + p[2] * s, p[1], -p[0] * s + p[2] * c];
}
function rz(p: [number, number, number], a: number): [number, number, number] {
  const c = Math.cos(a), s = Math.sin(a);
  return [p[0] * c - p[1] * s, p[0] * s + p[1] * c, p[2]];
}

function render(cols: number, rows: number, rot: [number, number, number]): string {
  // Head radius ~0.93; fill ~92% of the panel height.
  const headRadius = 0.93;
  const targetPixels = rows * 0.44; // ~44% of height is half-head
  const cellSize = (headRadius + 0.05) / targetPixels; // world units per cell (row unit)
  const halfCols = cols / 2, halfRows = rows / 2;
  const camZ = 2.6;
  const grid: { c: number; z: number }[] = new Array(cols * rows)
    .fill(0).map(() => ({ c: 0, z: -99 }));
  for (let i = 0; i < P.length; i++) {
    let p = P[i] as [number, number, number];
    p = rx(p, rot[0]);
    p = ry(p, rot[1]);
    p = rz(p, rot[2]);
    let n = N[i] as [number, number, number];
    n = rx(n, rot[0]);
    n = ry(n, rot[1]);
    n = rz(n, rot[2]);
    if (p[2] >= camZ - 0.01) continue;
    const pers = camZ / (camZ - p[2]);
    const gx = Math.round(halfCols + (p[0] * pers) / cellSize);
    const gy = Math.round(halfRows - (p[1] * pers) / cellSize);
    if (gx < 0 || gx >= cols || gy < 0 || gy >= rows) continue;
    const b = 0.3 + 0.65 * Math.max(n[0] * LIGHT[0] + n[1] * LIGHT[1] + n[2] * LIGHT[2], 0);
    const cell = grid[gy * cols + gx];
    if (p[2] > cell.z) { cell.z = p[2]; cell.c = Math.min(9, Math.floor(b * 10)); }
  }
  const lines: string[] = [];
  for (let gy = 0; gy < rows; gy++) {
    let line = '';
    for (let gx = 0; gx < cols; gx++) line += RAMP[grid[gy * cols + gx].c];
    lines.push(line);
  }
  return lines.join('\n');
}

console.log('\n=== FRONT (yaw 0) ===');
console.log(render(72, 36, [0, 0, 0]));
console.log('\n=== RIGHT (yaw -0.9) ===');
console.log(render(72, 36, [0, -0.9, 0]));
console.log('\n=== TOP (pitch +1.2) ===');
console.log(render(72, 36, [1.2, 0, 0]));